blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/mxc0bbn/agent-monitor-besclients/discussions
    about: For how-to questions, general discussion, or open-ended ideas, please use Discussions.
